// <auto-generated />
namespace EventsNTicketsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedTicketSeats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedTicketSeats));
        
        string IMigrationMetadata.Id
        {
            get { return "202109051217142_changedTicketSeats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
